// <auto-generated />
using System;
using BookManagement.Repository.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagement.Repository.Data.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250221125533_AgeProperty")]
    partial class AgeProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagement.Models.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATEDIFF(YEAR, PublicationYear, GETDATE())", false);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PublicationYear")
                        .HasColumnType("DATE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef924032-43a1-4531-ad96-5ee190790af8"),
                            Age = 0,
                            AuthorName = "Alexander Dumas",
                            PublicationYear = new DateTime(1844, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Three Musketers",
                            ViewCount = 5
                        },
                        new
                        {
                            Id = new Guid("b6a80edc-d005-47c6-8241-619109da1504"),
                            Age = 0,
                            AuthorName = "Fiodor Dostoevsky",
                            PublicationYear = new DateTime(1880, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Brothers Karamazov",
                            ViewCount = 11
                        },
                        new
                        {
                            Id = new Guid("522f3f16-5ae3-42ea-9c19-90995b097805"),
                            Age = 0,
                            AuthorName = "Miguel de Cervantes",
                            PublicationYear = new DateTime(1605, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Don Quixote",
                            ViewCount = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
